tCap/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('tCap_reviews/', include('tCap_reviews.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tCap_reviews/urls.py
from django.urls import path

from . import views

app_name = "tCap_reviews"
urlpatterns = [
    path('', views.index, name='index'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('searchAuthor', views.searchAuthor, name='searchAuthor'),
    path('searchOpus', views.searchOpus, name='searchOpus'),
    path('authors/<int:authorId>', views.authorPage, name='authorPage'),
    path('categories/<int:categoryId>', views.categoryPage, name='categoryPage'),
    path('opuses/<int:opusId>', views.opusPage, name='opusPage'),
    path('opuses/<int:opusId>/<int:reviewId>', views.reviewPage, name='reviewPage'),
    path('opuses/<int:opusId>/addReview', views.addReview, name='addReview'),
    path('opuses/<int:opusId>/<int:reviewId>/editReview', views.editReview, name='editReview'),
]

tCap_reviews/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth import get_user_model


class Nationality(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField(max_length=100)
    activityPeriod = models.CharField(max_length=30)
    description = models.CharField(max_length=1200)
    nationalityId = models.ForeignKey(Nationality, on_delete=models.RESTRICT)
    image = models.ImageField(upload_to='authorsImages/', blank=True, default='authorsImages/default.jpg')

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return self.name

class Opus(models.Model):
    name = models.CharField(max_length=100)
    categoryId = models.ForeignKey(Category, on_delete=models.RESTRICT)
    authorId = models.ForeignKey(Author, on_delete=models.CASCADE)
    description = models.CharField(max_length=1200)
    image = models.ImageField(upload_to='opusesImages/', blank=True, default='opusesImages/default.jpg')

    def __str__(self):
        return self.name

class Review(models.Model):
    content = models.CharField(max_length=15000)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)])
    userId = models.ForeignKey(get_user_model(), default=-1, on_delete=models.SET_DEFAULT)
    opusId = models.ForeignKey(Opus, on_delete=models.CASCADE)

    def __str__(self):
        return self.content[:50]

class Comment(models.Model):
    content = models.CharField(max_length=1500)
    userId = models.ForeignKey(get_user_model(), default=-1, on_delete=models.SET_DEFAULT)
    reviewId = models.ForeignKey(Review, on_delete=models.CASCADE)

    def __str__(self):
        return self.content[:50]

class OpusList(models.Model):
    name = models.CharField(max_length=100)
    userId = models.ForeignKey(get_user_model(), default=-1, on_delete=models.SET_DEFAULT)
    opuses = models.ManyToManyField(Opus)

    def __str__(self):
        return self.name

#to ewentualnie mozna wyrzucic
class UserRating(models.Model):
    userId = models.ForeignKey(get_user_model(), default=-1, on_delete=models.SET_DEFAULT)
    opusId = models.ForeignKey(Opus, on_delete=models.CASCADE)
    hoursToFinish = models.IntegerField(default=0)
    difficulty = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)])

tCap_reviews/forms.py
from django import forms
from django.forms import ModelForm
from .models import Review, Comment

RATING_CHOICES = (
      (1, '1'),
      (2, '2'),
      (3, '3'),
      (4, '4'),
      (5, '5'),
      (6, '6'),
      (7, '7'),
      (8, '8'),
      (9, '9'),
      (10, '10'),
  )

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ('content', 'rating')
        labels = {
            'content': '',
            'rating': 'Ocena',
        }
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'content'}),
            'rating': forms.Select(choices=RATING_CHOICES, attrs={'class': 'form-control'}),
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        labels = {
            'content': '',
        }
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'content'}),
        }

tCap_reviews/views.py
from django.contrib.auth import authenticate, get_user_model, login as auth_login, logout as auth_logout
from django.contrib.auth.models import Group
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Author, Opus, Category, Review, Comment
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from .forms import ReviewForm, CommentForm

def index(request):
    authorsList = Author.objects.all().order_by('name')
    categoriesList = Category.objects.all().order_by('name')
    context = {
        'authorsList': authorsList,
        'categoriesList': categoriesList,
    }
    return render(request, 'tCap_reviews/index.html', context)

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            group = Group.objects.get(name='Normies')
            group.user_set.add(user)
            messages.success(request, ("Zarejestrowano pomyślnie, teraz możesz się zalogować"))
            return redirect('tCap_reviews:index')
    else:
        form = UserCreationForm()

    return render(request, 'tCap_reviews/register.html', {
        'form': form,
    })

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('tCap_reviews:index')
            else:
                return redirect('tCap_reviews:login')
    else:
        form = AuthenticationForm()

    return render(request, 'tCap_reviews/login.html', {
        'form': form,
    })

def logout(request):
    auth_logout(request)
    messages.success(request, ("Wylogowano pomyślnie!"))
    return redirect('tCap_reviews:index')

def searchAuthor(request):
    if request.method == "POST":
        searchedPhrase = request.POST['searchedPhrase']
        results = Author.objects.filter(name__contains=searchedPhrase)
        return render(request, 'tCap_reviews/searchAuthor.html', {
            'results': results,
        })
    else:
        return redirect('tCap_reviews:index')

def searchOpus(request):
    if request.method == "POST":
        searchedPhrase = request.POST['searchedPhrase']
        results = Opus.objects.filter(name__contains=searchedPhrase)
        return render(request, 'tCap_reviews/searchOpus.html', {
            'results': results,
        })
    else:
        return redirect('tCap_reviews:index')

def authorPage(request, authorId):
    author = get_object_or_404(Author, id=authorId)
    #authorOpuses = get_list_or_404(Opus, authorId=author.id)
    authorOpuses = Opus.objects.filter(authorId=author.id)
    context = {
        'author': author,
        'authorOpuses': authorOpuses
    }
    return render(request, 'tCap_reviews/authorPage.html', context)

def categoryPage(request, categoryId):
    category = get_object_or_404(Category, id=categoryId)
    categoryOpuses = get_list_or_404(Opus, categoryId=category.id)
    context = {
        'category': category,
        'categoryOpuses': categoryOpuses
    }
    return render(request, 'tCap_reviews/categoryPage.html', context)

def opusPage(request, opusId):
    opus = get_object_or_404(Opus, id=opusId)
    opusReviews = Review.objects.filter(opusId=opusId)
    reviewsList = []
    for review in opusReviews:
        reviewer = get_object_or_404(get_user_model(), id=review.userId_id)
        reviewsList.append((review.id, reviewer.username, review.rating))
    didUserSubmittedReview = False
    userReview = None
    if request.user.is_authenticated and request.user.is_staff:
        try:
            userReview = Review.objects.get(opusId=opusId, userId=request.user.id)
        except:
            userReview = None
        if userReview is not None:
            didUserSubmittedReview = True
    context = {
        'opus': opus,
        'didUserSubmittedReview': didUserSubmittedReview,
        'userReview': userReview,
        'reviewsList': reviewsList,
    }
    return render(request, 'tCap_reviews/opusPage.html', context)

def reviewPage(request, opusId, reviewId, wasCommentSubmitted=False):
    opus = get_object_or_404(Opus, id=opusId)
    review = get_object_or_404(Review, id=reviewId)
    reviewer = get_object_or_404(get_user_model(), id=review.userId_id)
    reviewComments = Comment.objects.filter(reviewId=review.id)
    commentsList = []
    for comment in reviewComments:
        user = get_object_or_404(get_user_model(), id=comment.userId_id)
        commentsList.append((comment.id, user.username, comment.content))

    if request.method == "POST" and not wasCommentSubmitted:
        commentForm = CommentForm(request.POST)
        if commentForm.is_valid():
            comment = commentForm.save(commit=False)
            comment.reviewId = review
            comment.userId = request.user
            comment.save()
            wasCommentSubmitted = True
            return reviewPage(request, opusId, reviewId, wasCommentSubmitted)
    else:
        commentForm = CommentForm

    context = {
        'opus': opus,
        'review': review,
        'reviewer': reviewer,
        'commentsList': commentsList,
        'commentForm': commentForm,
    }
    return render(request, 'tCap_reviews/reviewPage.html', context)

def addReview(request, opusId):

    if not request.user.is_staff or not request.user.is_authenticated:
        return redirect('tCap_reviews:index')

    opus = get_object_or_404(Opus, id=opusId)
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.opusId = opus
            review.userId = request.user
            review.save()
            return opusPage(request, opusId)
    else:
        form = ReviewForm

    return render(request, 'tCap_reviews/addReview.html', {
        'form': form,
        'opus': opus,
    })

def editReview(request, opusId, reviewId):

    if not request.user.is_staff or not request.user.is_authenticated:
        return redirect('tCap_reviews:index')

    review = Review.objects.get(id=reviewId)
    opus = get_object_or_404(Opus, id=opusId)

    form = ReviewForm(request.POST or None, instance=review)
    if form.is_valid():
        review = form.save(commit=False)
        review.opusId = opus
        review.userId = request.user
        review.save()
        return opusPage(request, opusId)

    return render(request, 'tCap_reviews/editReview.html', {
        'form': form,
        'opus': opus,
        'review': review,
    })

templates/tCap_reviews/addReview.html
{% extends "tCap_reviews/base.html" %}

{% block title %}Dodawanie recenzji{% endblock %}

{% block content %}
    <h1>Dodajesz recenzję tekstu {{ opus.name }}</h1>
    <br/><br/>
    <form action="" method=POST>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Dodaj" class="btn btn-secondary">
    </form>
{% endblock %}

templates/tCap_reviews/authorPage.html
{% extends "tCap_reviews/base.html" %}

{% block title %}{{ author.name }}{% endblock %}

{% block content %}
    <h1>{{ author.name }}</h1>
    <img src="{{ author.image.url }}" height=300>
    <h3>Narodowość: {{ author.nationalityId }}</h3>
    <h3>Lata aktywności: {{ author.activityPeriod }}</h3>
    <p>{{ author.description }}</p>
    <h3>Teksty autora:</h3>
    {% for opus in authorOpuses %}
        <li><a href="{% url 'tCap_reviews:opusPage' opus.id %}">{{ opus.name }}</a></li>
    {% endfor %}
{% endblock %}

templates/tCap_reviews/base.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>{% block title %}ReReviews{% endblock %}</title>
  </head>
  <header style="background-color:skyblue">
    <a href="{% url 'tCap_reviews:index' %}">Strona główna</a></br>
    {% if user.is_authenticated %}
        <a href="{% url 'tCap_reviews:logout' %}">Wyloguj się!</a>
    {% else %}
        <a href="{% url 'tCap_reviews:register' %}">Zarejestruj się!</a></br>
        <a href="{% url 'tCap_reviews:login' %}">Zaloguj się!</a>
    {% endif %}
    <form class="d-flex" method=POST action="{% url 'tCap_reviews:searchAuthor' %}">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Wyszukaj twórcę" aria-label="Search" name="searchedPhrase">
        <button class="btn btn-outline-secondary" type="submit">Szukaj</button>
    </form>
    <form class="d-flex" method=POST action="{% url 'tCap_reviews:searchOpus' %}">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Wyszukaj tekst" aria-label="Search" name="searchedPhrase">
        <button class="btn btn-outline-secondary" type="submit">Szukaj</button>
    </form>
  </header>
  {% block msg %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <p style="background-color:blueviolet ; font-size:200% ; text-align:center">{{ message }}</p><br>
        {% endfor %}
    </ul>
    {% endif %}
  {% endblock %}
  <body>
    {% block content %}
    {% endblock %}
  </body>
</html>

templates/tCap_reviews/categoryPage.html
{% extends "tCap_reviews/base.html" %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <h1>{{ category.name }}</h1>
    <h3>Teksty z danej kategorii:</h3>
    {% for opus in categoryOpuses %}
        <li><a href="{% url 'tCap_reviews:opusPage' opus.id %}">{{ opus.name }}</a></li>
    {% endfor %}
{% endblock %}

templates/tCap_reviews/editReview.html
{% extends "tCap_reviews/base.html" %}

{% block title %}Edytowanie recenzji{% endblock %}

{% block content %}
    <h1>Edytujesz recenzję tekstu {{ opus.name }}</h1>
    <br/><br/>
    <form action="" method=POST>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Zapisz zmiany" class="btn btn-secondary">
    </form>
{% endblock %}

templates/tCap_reviews/index.html
{% extends "tCap_reviews/base.html" %}

{% block title %}ReReviews{% endblock %}

{% block content %}
    <h1>Cześć, witamy na ReReviews!</h1>
    <h3>Przeglądaj teksty z wybranej kategorii:</h3>
    {% for category in categoriesList %}
            <li><a href="{% url 'tCap_reviews:categoryPage' category.id %}">{{ category.name }}</a></li>
        {% endfor %}
    <h3>Odkrywaj twórców:</h3>
    {% for author in authorsList %}
            <li><a href="{% url 'tCap_reviews:authorPage' author.id %}">{{ author.name }}</a></li>
        {% endfor %}
{% endblock %}

templates/tCap_reviews/login.html
{% extends "tCap_reviews/base.html" %}

{% block title %}Logowanie{% endblock %}

{% block content %}
    {% if form.errors %}
      <p style="color:darkred">Błędne dane logowania!</p>
    {% endif %}

  <h2>Zaloguj się</h2>
  <form action="{% url 'tCap_reviews:login' %}" method="POST">
	{% csrf_token %}
	{{ form.as_p }}
    <br>
	<input type="submit" value="Zatwierdź" class="btn btn-secondary" />
  </form>
{% endblock %}

templates/tCap_reviews/opusPage.html
{% extends "tCap_reviews/base.html" %}

{% block title %}{{ opus.name }}{% endblock %}

{% block content %}
    <h1>{{ opus.name }}</h1>
    <img src="{{ opus.image.url }}" height=300>
    <h3>Kategoria tekstu: {{ opus.categoryId }}</h3>
    <h3>Autor tekstu: <a href="{% url 'tCap_reviews:authorPage' opus.authorId_id %}">{{ opus.authorId }}</a></h3>
    <p>{{ opus.description }}</p>
    </br></br>
    {% if user.is_authenticated and user.is_staff %}
        {% if didUserSubmittedReview %}
            <h3><a href="{% url 'tCap_reviews:editReview' opus.id userReview.id %}">Edytuj swoją recenzję tego tekstu</a></h3>
        {% else %}
            <h3><a href="{% url 'tCap_reviews:addReview' opus.id %}">Dodaj recenzję tego tekstu</a></h3>
        {% endif %}
    {% endif %}
    {% for review in reviewsList %}
            <li><a href="{% url 'tCap_reviews:reviewPage' opus.id review.0 %}">Recenzja użytkownika {{ review.1 }}</a> (wystawiono ocenę {{ review.2 }})</li>
        {% endfor %}
{% endblock %}

templates/tCap_reviews/register.html
{% extends "tCap_reviews/base.html" %}

{% block title %}Rejestracja{% endblock %}

{% block content %}
    {% if form.errors %}
      <p style="color:darkred">Formularz rejestracji został uzupełniony niepoprawnie!</p>
    {% endif %}

  <h2>Zarejestruj się</h2>
  <form action="{% url 'tCap_reviews:register' %}" method="POST">
	{% csrf_token %}
	{{ form.as_p }}
    <br>
	<input type="submit" value="Zatwierdź" class="btn btn-secondary" />
  </form>
{% endblock %}

templates/tCap_reviews/reviewPage.html
{% extends "tCap_reviews/base.html" %}

{% block title %}{{ opus.name }}{% endblock %}

{% block content %}
    <h1>Recenzja tekstu {{ opus.name }} napisana przez eksperta {{ reviewer.username }}</h1>
    <img src="{{ opus.image.url }}" height=300>
    <p>{{ review.content }}</p>
    <h1>Ocena: {{ review.rating }}</h1>
    </br></br>
    <h3>Komentarze:</h3>
    {% for comment in commentsList %}
        <li>
        <b>{{ comment.1 }}</b>
        </br>{{ comment.2 }}
        </li>
    {% endfor %}
    {% if user.is_authenticated %}
        <h3>Dodaj swój komentarz:</h3>
        <form action="" method=POST>
            {% csrf_token %}
            {{ commentForm.as_p }}
            <input type="submit" value="Skomentuj" class="btn btn-secondary">
        </form>
    {% endif %}
{% endblock %}

templates/tCap_reviews/searchAuthor.html
{% extends "tCap_reviews/base.html" %}

{% block title %}Wyszukani twórcy{% endblock %}

{% block content %}
    <h3>Wyszukani twórcy:</h3>
    {% for author in results %}
            <li><a href="{% url 'tCap_reviews:authorPage' author.id %}">{{ author.name }}</a></li>
        {% endfor %}
{% endblock %}

templates/tCap_reviews/searchOpus.html
{% extends "tCap_reviews/base.html" %}

{% block title %}Wyszukane teksty{% endblock %}

{% block content %}
    <h3>Wyszukane teksty:</h3>
    {% for opus in results %}
            <li><a href="{% url 'tCap_reviews:opusPage' opus.id %}">{{ opus.name }}</a></li>
        {% endfor %}
{% endblock %}